version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/Mople
permissions:
  - object: /home/ubuntu/Mople
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: ./deploy.sh
      timeout: 60
      runas: ubuntu
