version: 0.0
os: linux

files:
  - source: /
    destination: /opt/ghwns6743
permissions:
  - object: /opt/ghwns6743/
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 120
      runas: root
