name: Deploy master
on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
            java-version: '11'
            distribution: 'temurin'

      - name: Grant Excute permission for gradlew
        run:  chmod +x ./gradlew
        shell : bash
        
      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash
        
      - name: Current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDHH-mm-ss
          utcOffset: "+09:00"
        
      - name: Generate package
        run: |
          mkdir -p deploy
          cp build/libs/boilerplate-0.0.1-SNAPSHOT.jar deploy/application.jar
          cp Procfile deploy/Procfile
          cp -r .ebextensions deploy/.ebextensions
          cd deploy && zip -r deploy.zip .

#        cp -r .platform deploy/.platform
        
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.EB_AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.EB_AWS_SECRET_ACCESS_KEY }}
          application_name: eb-hojun
          environment_name: Ebhojun-env
          version_label: ${{github.SHA}}
          region: ap-northeast-2
          deployment_package: deploy/deploy.zip
