name: deploy1

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with: 
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'

          
        
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build

      # 전송할 파일을 담을 디렉토리 생성
      - name: Make Directory
        run: mkdir -p deploy

        # Jar 파일 복사
      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy

      # appspec.yml 파일 복사
      - name: Copy appspec.yml
        run: cp appspec.yml ./deploy

      - name: Copy script
        run: cp deploy.sh ./deploy

        # 파일 압축
      - name: Make zip file
        run: zip -r ./springboot-intro-build.zip ./deploy

      - name: Deliver to AWS S3
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
        run: |
            aws s3 cp \
            --region ap-northeast-2 \
            --acl private ./springboot-intro-build.zip s3://ghwns6743/


      - name: Deploy
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
        run: |
            aws deploy create-deployment \
            --application-name ghwns6743 \
            --deployment-group-name ghwns6743 \
            --file-exists-behavior OVERWRITE \
            --s3-location bucket=ghwns6743,bundleType=zip,key=springboot-intro-build.zip \
            --region ap-northeast-2


          
